### PR TITLE
Auth with laravel

### PR DESCRIPTION
**Pull request by 3ddm3g**
I'm done writing the auth system in React. @TheHagen98 you can now write the unittests for
```
app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/Auth/RegisterController.php
resources/js/components/Auth/Login.jsx
resources/js/components/Auth/Register.jsx

```

### CODE REVIEW

**Comment by mamutuberalles** [comment]
Apporved!

**Comment by TheHagen98** [comment]
Okay, I work on it

**Review by mamutuberalles — APPROVED** [review]
Awesomesauce

**Review by rozafaz — APPROVED** [review]
Great work

**Review by TheHagen98 — APPROVED** [review]
Cool

**Pull request merged**
