### PR TITLE
Login & register

### PR DESCRIPTION
**Pull request by 3ddm3g**
# I'm done writing the full-stack of the login/register system, and it's ready to merge.

# Important files/changes:

### app/Http/Controllers/UserController.php
- Here i created the backend for the login/register forms (hopefully, we don't have to touch them anymore)
- I also put here a `getFeed()` function which is responsible for accessing the `feed` view (it is only referenced in the `routes/web.php` file). However if we start working on the feed, we might want to create a separate controller for it, which means this function will more likely be belong there.

### User model and DB migration
- I created the User model with it's corresponding database migration. At this time it only stores essential data like: `id`, `username`, `email`, `password` and `rememberToken`. 
- see `database/migrations/2022_10_02_200416_create_users_table`

### Routes
- In the file `routes/web.php` you can see all the routes i created for the system
- The feed view is right now accessible through the `/` route, accessing it is subject to logging in.
- You can narrow down access to logged in users only, by using the `auth` middleware on your routes.
- You can also do this for the opposite with the `guest` middleware. eg.: the `login` and `register` routes are inaccessible for logged in users, and they automatically get redirected back to `/`.

### Global frontend changes
- I made a `master` layout which we could use across every page. I included a lot of useful tools like bootstrap and popper. (see `resources/views/layouts/master.blade.php`)
- See the usage in the login/register pages.
- I also created a global custom stylesheet which you can find at `public/css/style.css`. 
- I added a `feed.blade.php` as a placeholder. I left it there, as right now this is the main page after the user logs in, and we could make the actual feed here.
- I also created a navigation bar (right now) for the sole purpose of having the logout button, but obviously it needs to be completely redesigned (I didn't want to do it in this branch, as global design wasn't the main purpose of this branch). [see `resources/views/includes/header.blade.php`]

### Login / register exclusive frontend
- You can find the login / register views in `resources/views`
- There's also an include (`resources/views/includes/display_errors.blade.php`) which is responsible for displaying error messages below input fields

If you have any remarks, write a comment.

### CODE REVIEW

**Comment by mamutuberalles** [comment]
Impressive! Very nice!

**Comment by mamutuberalles** [comment]
[BUG]

Please check the attached excerpt from my Terminal and get back to me.
[bug.txt](https://github.com/3ddm3g/TheNeighboursRecipeBook/files/9754432/bug.txt)

**Comment by 3ddm3g** [comment]
> [BUG]
> 
> Please check the attached excerpt from my Terminal and get back to me. [bug.txt](https://github.com/3ddm3g/TheNeighboursRecipeBook/files/9754432/bug.txt)

Hi! It seems to be a database misconfiguration in the `.env` file.
Are your database credentials typed in correctly in the `.env` file? [check with this](https://laravel.com/docs/9.x/database#configuration)
If yes, but it still occurs and you are using a local database, try setting `DB_HOST` to `localhost` instead of `127.0.0.1`.
It helped some people according to [this](https://stackoverflow.com/questions/35394230/sqlstatehy000-2002-connection-refused-within-laravel-homestead)

**Comment by 3ddm3g** [comment]
> Wow cool! Should we upload the wireframe to the readme file as planning reference or something or just to the final documentation?
Sounds good! Do you want to push them to master?

**Pull request merged**
